### PR TITLE
Update security.php

### PR DESCRIPTION
**Pull request by pbearne**
removed not need parm ($user) from the function as the calling action doesn't pass it

### CODE REVIEW

**Comment by simonwheatley** [comment]
@pbearne Looking at the WordPress [source code](https://github.com/WordPress/WordPress/blob/fdc538940dc02b2c956e9306e45c6c3fe8c7cf37/wp-includes/user.php#L102), the `wp_login` action does pass the `WP_User` object. Can you expand on what issues you're seeing here, please?

**Comment by simonwheatley** [comment]
I'm closing this issue, please re-open this if you have any specific problems that this is causing.

**Comment by pbearne** [comment]
Hi Sorry I missed the comment

We are/were call the action in our code without the second parm so I will change the call to pass the user

But I will point out that you are not using the $user in the function so the patch still stands 

Paul

**Comment by simonwheatley** [comment]
Hi again @pbearne :smile: 

We decided not to implement the changes in this PR for the following reasons:

> We generally prefer matching the arguments to what gets sent to the function...meaning, if a function is going to be called consistently with 2 arguments, then the function definition may as well write them in, whether it uses them or not, for the sake of the maintainer that comes along to do refactoring and wonders what args get passed.
> 
> It doesn't cost anything, and makes the function definition consistent with how it's used - it's a clear indication to the developer what the action sends.
> 
> Not defining it does have a cost - that's the difference between glancing at the code and knowing it also gets the `$user` and getting confused and resorting to searching the action in the docs.
> 
> actions/filters are a little tricky because they allow variable numbers of arguments...my thought is to always optimize for the developer though - reduce the amount of brainpower necessary to make changes to that action. If it can get a second arg, we may as well send it even if we're not using it at this moment, to save the maintainer a few brain cycles if they want to start using it.

Hope this helps explain our decision. Thanks again for sending the PR, don't hesitate to do so in the future.

**Pull request closed without merging**
